- name: A playbook to install and start minikube
  hosts: localhost
  user: ubuntu
  become: no

  tasks:
  - name: Install minikube
    shell:
      cmd: curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64

  - name: Change ownership
    shell:
      cmd: chmod +x minikube

  - name: Move minikube to bin
    shell:
      cmd: sudo mv minikube /usr/local/bin/

  - name: Start minikube
    shell:
      cmd: minikube start
